### ISSUE TITLE
Nestful::UnauthorizedAccess: Failed.  Response code = 401.  Response message = Unauthorized

### ISSUE THREAD

**Issue by cs0511** [Pazienti/humanapi#3]
Hi @AndreaPaciolla 

I am using your great gem in our project. Thank you for all your works.

Recently I found an issue that when I try to request to humanapi, for example 
```
User.second.human.query(:weight)
```

It will return me 
```
Nestful::UnauthorizedAccess: Failed.  Response code = 401.  Response message = Unauthorized.  Response Body = {"code":401,"error":"invalid_token","message":"The API token is not valid. It might have been revoked or refreshed."}.
```

It just happens in my AWS(amazon server). It works fine at my personal MAC. I tried curl command to humanAPI which also works. Also tried [Typhoeus](https://github.com/typhoeus/typhoeus) which works too.

Do you have any clue? If not, I have to discard this gem, even if I don't want to.

Thank you again, great work.

**Comment by cs0511** [comment]
Please close this issue. It's my fault that I used an invalid accessToken. 

@AndreaPaciolla

**Comment by cs0511** [comment]
thanks @alessiosantocs , sorry for taking your time.

**Comment by alessiosantocs** [comment]
no worries at all @cs0511. Sorry if I couldn't answer earlier!
